### DISCUSSION TITLE
Using Stunner for a webrtc broadcaster

### DISCUSSION THREAD

**Discussion by nunoribeiro-tw** [l7mp/stunner#166] [Q&A]
I am trying to run the following setup
A device A is sending video to a cluster on device B. On this cluster we have a stunner running and a webrtc broadcast that receives the incoming stream from device A and broadcasts it to whomever connects to it afterwards. Currently we have 2 pods in the cluster connecting to the broadcast and consuming the stream without problem. However when we try to add a browser (either on device A or a device C) to consume from the broadcast there are some issues where the stunner doesnt seem to be able to provide a viable path for the ice connection to be established. 

Am I missing something in how the stunner is supposed to work? Should this scenario be doable or is there something that makes this undoable?

kubernetes setup: 
I am working on a Arm Mac so I am using multipass with kubeadm to run the cluster and portforwarding the service ports for local network access

**Comment by levaitamas** [comment]
My understanding is: you can connect to your broadcast app in k8s via STUNner from device A. Pods inside your cluster can reach the broadcast app too. The problem is, a webbrowser outside on the cluster cannot reach the broadcast app via STUNner.

If that's the situation, my first assumption is there is an error in the ICE process at your browser side. I recommend to check your ICE candidates with webrtc-internals (`chrome://webrtc-internals` in Chromium/Chrome) first. BTW what is the broadcast app? 

Last but not least, if it is not a secret, mind to tell a bit about your use case. Thanks!

**Reply by nunoribeiro-tw** [reply]
> My understanding is: you can connect to your broadcast app in k8s via STUNner from device A. Pods inside your cluster can reach the broadcast app too. The problem is, a webbrowser outside on the cluster cannot reach the broadcast app via STUNner.

Yes that's it. We get the ICE candidates on the browser but then the connection is not established. 

> If that's the situation, my first assumption is there is an error in the ICE process at your browser side. I recommend to check your ICE candidates with webrtc-internals (`chrome://webrtc-internals` in Chromium/Chrome) first. BTW what is the broadcast app?

So the broadcast is based on this https://github.com/webrtc-rs/webrtc/tree/master/examples/examples/broadcast
It receives the video from outside of the cluster and acts as a relay so the device A doesn't have to create multiple streams

> Last but not least, if it is not a secret, mind to tell a bit about your use case. Thanks!

I'm not sure if I can share it for now but will ask


Some more info originally I was using a UDP gateway but since a different device needs to access the port and from my understanding doing a kubectl port-forward doenst work for upd ports I created a TCP gateway instead. Not sure if this could be causing udp vs tcp issues somewhere. I also recently added the ice_transport_policy to be relay

**Reply by levaitamas** [reply]
I see. The broadcast example page leads me to this jsfiddle site: https://jsfiddle.net/1jc4go7v/
This client uses google's stun server by default:
```js
  let pc = new RTCPeerConnection({
    iceServers: [
      {
        urls: 'stun:stun.l.google.com:19302'
      }
    ]
  })
```

You need to adapt it to use STUNner. I recomend to check this [doc](https://github.com/l7mp/stunner/blob/main/docs/AUTH.md) and the [stunner-auth-service](https://github.com/l7mp/stunner-auth-service).

**Reply by nunoribeiro-tw** [reply]
Yeah I am not using the broadcaster copy paste we adapted to our scenario and replaced the ICE with our stunner

```
let config = RTCConfiguration {
        ice_servers: vec![RTCIceServer {
            urls: vec!["turn:192.168.1.165:3478?transport=tcp".to_owned()],
            username: "user-1".to_owned(),
            credential: "pass-1".to_owned(),
            credential_type: RTCIceCredentialType::Password,
        }]
        .into(),
        ..Default::default()
    };
```

Something like this for the rust apps for example

**Reply by nunoribeiro-tw** [reply]
So this is one of the ICE candidates we get on the web browser and we also succesfully send it to the broadcast

```
candidate: 
  RTCIceCandidate
  address: "10.44.0.7"
  candidate:  "candidate:834171966 1 udp 16785407 10.44.0.7 51824 typ relay raddr 0.0.0.0 rport 0 generation 0 ufrag r7VI network-cost 999"
  component: "rtp"
  foundation: "834171966"
  port: 51824
  priority: 16785407
  protocol: "udp"
  relatedAddress: "0.0.0.0"
  relatedPort: 0
  relayProtocol: "tcp"
  sdpMLineIndex: 0
  sdpMid: "0"
  tcpType: null
  type: "relay"
  url: "turn:192.168.1.165:3478?transport=tcp"
  usernameFragment: "r7VI"
```

**Reply by nunoribeiro-tw** [reply]
my stunner.yaml

```
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: stunner-gatewayclass
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    group: "stunner.l7mp.io"
    kind: GatewayConfig
    name: stunner-gatewayconfig
    namespace: stunner
  description: "STUNner is a WebRTC media gateway for Kubernetes"

---

apiVersion: stunner.l7mp.io/v1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig
  namespace: stunner
spec:
  realm: stunner.l7mp.io
  authRef:
    name: stunner-auth-secret
    namespace: stunner

---

apiVersion: v1
kind: Secret
metadata:
  name: stunner-auth-secret
  namespace: stunner
type: Opaque
stringData:
  type: static
  username: user-1
  password: pass-1

---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: udp-gateway
  namespace: stunner
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: TURN-UDP
      

---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: tcp-gateway
  namespace: stunner
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: tcp-listener
      port: 3478
      protocol: TURN-TCP

---

apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: media-plane
  namespace: stunner
spec:
  parentRefs:
    - name: udp-gateway
    - name: tcp-gateway
  rules:
    - backendRefs:
        - name: media-plane
          namespace: default
```
