### ISSUE TITLE
Cannot apply GatewayClass from README.md on K8s v1.27

### ISSUE THREAD

**Issue by Schille** [l7mp/stunner#101]
Applying this `GatewayClass` from your README.md 
```
kubectl apply -f - <<EOF
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: stunner-gatewayclass
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    group: "stunner.l7mp.io"
    kind: GatewayConfig
    name: stunner-gatewayconfig
    namespace: stunner
  description: "STUNner is a WebRTC media gateway for Kubernetes"
EOF
```
raises a webhook error on GKE Autopilot 1.27

```
Error from server (InternalError): error when creating "STDIN": Internal error occurred: failed calling webhook "gateway-api-alpha-deprecated-use-beta-version.gke.io": failed to call webhook: Post "https://gateway-api-alpha-deprecated-use-beta-version.kube-system.svc:443/?timeout=1s": service "gateway-api-alpha-deprecated-use-beta-version" not found
```

Using `apiVersion: gateway.networking.k8s.io/v1beta1` works.

The same is with `Gateway`. 
However, `UDPRoute` only works with `v1alpha2`.

`kubectl version --short`
```
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.27.3-gke.100
```
