### ISSUE TITLE
On GKE, how to specify an IP for udp-gateway

### ISSUE THREAD

**Issue by nhha1602** [l7mp/stunner#106]
Dear All,

I tried to deploy stunner on GKE. As your docs, when apply file stunner-helm/livekit-call-stunner.yaml, it will auto create an udp-gateway service then it will auto get an IP. But I want to specify an IP for it as below that I did, but it still get a different IP.

```
apiVersion: stunner.l7mp.io/v1alpha1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig
  namespace: stunner-dev
spec:
  realm: stunner.l7mp.io
  authType: plaintext
  userName: "user-1"
  password: "pass-1"
  loadBalancerServiceAnnotations:
    networking.gke.io/load-balancer-type: Internal

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: udp-gateway
  namespace: stunner-dev
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: TURN-UDP
  addresses:
    - type: NamedAddress
      value: my_reserved_ip4
```

The "my_reserved_ip4" created by command:

```
gcloud compute addresses create IP_ADDRESS_NAME \
    --purpose=SHARED_LOADBALANCER_VIP \
    --region=COMPUTE_REGION \
    --subnet=SUBNET \
    --project=PROJECT_ID
```

Could you, please help.

Thanks and regards.

**Comment by rg0now** [comment]
Using a fix external IP is, theoretically, supported by STUNner, but this is something that is not quite standardized across cloud providers and so we haven't tested this feature extensively yet.

The problem is that the address type you're using in the Gateway spec (`NamedAddress`) is [deprecated](https://github.com/kubernetes-sigs/gateway-api/blob/de8675f27a35bae354027a832b1335cc167a96c2/apis/v1/shared_types.go#L682) and so we currently [do not accept `NamedAddress` as the address type](https://github.com/l7mp/stunner-gateway-operator/blob/e7fe7384ca8b8c1fe48fa5effe315d25eba8ad0d/internal/renderer/service_util.go#L325).

I have two suggestions.

First, try to replace the `NamedAddress` type with `IPAddress` as in the below, hoping that GKE would accept it:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: udp-gateway
  namespace: stunner-dev
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: TURN-UDP
  addresses:
    - type: IPAddress
      value: my_reserved_ip4
```

The other idea would be to create the LB Service manually (just copy-paste the YAML of the `udp-gateway` Service) and set the fields `spec.externalIPs` and `spec.loadBalancerIP` to the IP address you got from GKE. Would this work? Can you reach STUNner now over that IP? If you do then it is a quick patch to change the code to accept `NamedAddress`, that would at least fix GKE.

Also, can you please copy-paste the YAML of the service STUNner has created (`kubectl -n stunner-dev get svc udp-gateway -o yaml`)?

**Comment by rg0now** [comment]
It just occurred to me that you could [query the IP address](https://cloud.google.com/sdk/gcloud/reference/compute/addresses/list) assigned by `gcloud compute addresses create ...`, let the result be `A.B.C.D`. Then, set this IP with type `IPAddress` in the Gateway `spec.addresses`:

```
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: udp-gateway
  namespace: stunner-dev
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: TURN-UDP
  addresses:
    - type: IPAddress
      value: A.B.C.D
```

It seems the `NamedAddress` type is not supported outside Google's own in-house load-balancers and, regrettably, we're not Google. Would this solution work for you?
