### ISSUE TITLE
Is stunner FedRamp compliant?

### ISSUE THREAD

**Issue by maksimu** [l7mp/stunner#119]
Just a random question, does any body know if stunner will be approved to run in AWS FedRamp and then pass the audit? Any thoughts would be welcomed.

https://aws.amazon.com/compliance/fedramp/

**Comment by rg0now** [comment]
Currently there's no plan due to a lack of resources and financing, but we're not against it at all if there is a strong interest. Could you please give us motivations to go down that path? Is the lack if an audit blocking you from adopting STUNner?

**Comment by rg0now** [comment]
Thanks. One minor note: if you aim to deploy into Kubernetes then don't mess with coturn, STUNner is much better suited for anything cloud-native. So the question is not "coturn vs STUNner", but rather "shall we use Kubernetes for hosting our WebRTC service"? If the answer is no then coturn may be the better option. But if it's Kubernetes it will be an endless pain supporting (let alone automatically scaling) it.  

Just my (biased) 2 cents of course.

**Comment by rg0now** [comment]
Feel free to reopen if anything new comes up. We really need your input on this

**Comment by rg0now** [comment]
This setup will work only if you want to deploy STUNner over a public IP, but then you will have to deploy the dataplane into the [host-network namespace](https://stackoverflow.com/a/77111602/1062914) like this:

```
apiVersion: stunner.l7mp.io/v1
kind: Dataplane
metadata:
  name: default
spec:
  command:
  - stunnerd
  args:
  - -w
  - --udp-thread-num=32
  image: l7mp/stunnerd:dev
  hostNetwork: true
  resources:
    limits:
      cpu: 6      # make this as big as your nodes support
      memory: 2Gi # ditto
    requests:
      cpu: 6      # ditto
      memory: 2Gi # ditto                                 
```

However, this is not the way most people deploy STUNner and very often it may not work as expected (in Kubernetes you *never* run pods on public IPs: it's not needed). So we recommend a better model that we call [symmetric ICE mode](https://github.com/l7mp/stunner/blob/main/docs/DEPLOYMENT.md#symmetric-ice-mode): let all clients create a TURN allocation and let STUNner connect them. For this you don't need public IPs at all (apart from the single IP provided by the cloud load-balancer that is shared by *all* STUNner pods). Here is a [detailed walkthrough](https://github.com/l7mp/stunner/tree/main/docs/examples/direct-one2one-call) to implement this.
