### ISSUE TITLE
Allow Gateways to request a specific NodePort in the automatically created Service 

### ISSUE THREAD

**Issue by rg0now** [l7mp/stunner#137]
Several users requested for a way to enforce a specific NodePort when exposing a Gateway. This can be done by, say, adding the annotation `stunner.l7mp.io/nodeport: <my-nodeport>` that would the operator consider when creating the Service. Enforcing a NodePort that is already used is an error.

This issue is to track the progress in implementing this feature.

**Comment by smeng9** [comment]
We also need to consider the case of complex-gateway with multiple listeners. Then we probably need multiple node ports.

**Comment by rg0now** [comment]
Hmm, very good point, thx! What about a list of key-value pairs in the annotation value like `stunner.l7mp.io/nodeport: ["udp-listener":32000,"tcp-listener":32001,"tls-listener":32002,"dtls-listener":32003]`, where each key-value pair is a name of a listener and a requested nodeport? Wdyt?

**Comment by smeng9** [comment]
Sounds good to me

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rg0now** [comment]
This is now implemented in https://github.com/l7mp/stunner-gateway-operator/commit/b92ef6a99766c5ac0b3fadcf94aca8e2bb9f55f0, you can install it from the [`dev`](https://github.com/l7mp/stunner/blob/main/docs/INSTALL.md#development-version) channel. Dear @smeng9, can you please test this and report any problem you find?

**Comment by smeng9** [comment]
Hi @rg0now sorry for late reply

I have performed some test and seems there are some issues creating the `service/complex-gateway` in 0.19.0

Here is the list of what kubernetes resources originally I had in 0.18.0 . In 0.18.0 I manually used kube edit to change the node port number of `service/complex-gateway` after a deploy.
<img width="892" alt="Screenshot 2024-06-06 at 11 34 39 AM" src="https://github.com/l7mp/stunner/assets/38666763/6042d3da-44fa-45d4-8e11-722c15c8846a">

I used the annotation in 0.19.0 but I cannot find the `service/complex-gateway` anymore
<img width="639" alt="Screenshot 2024-06-06 at 11 33 25 AM" src="https://github.com/l7mp/stunner/assets/38666763/dae53b63-1d67-4514-896e-88561eda511c">

Here is my config. I realized there are some changes are not very clear in the doc, first stunner.l7mp.io/enable-mixed-protocol-lb type seems gets changed from boolean to a string. Second I have to add escapes to the stunner.l7mp.io/nodeport.
```
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: complex-gateway
  namespace: stunner
  annotations:
    stunner.l7mp.io/enable-mixed-protocol-lb: "true"
    stunner.l7mp.io/nodeport: "{\"udp-listener\":31478,\"tcp-listener\":31479}"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "8086"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/live"
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 31478
      protocol: TURN-UDP
      allowedRoutes:
        namespaces:
          from: All
    - name: tcp-listener
      port: 31479
      protocol: TURN-tcp
      allowedRoutes:
        namespaces:
          from: All

```

Is there way I can troubleshoot the service/complex-gateway not showing up?
