### ISSUE TITLE
Intermittent disconnections after updates

### ISSUE THREAD

**Issue by caffeinism** [l7mp/stunner#168]
### Description

Upgrading stunnerd's container image from 0.20 to 0.21 (or dev) causes unpredictable disconnections. No issues at all with 0.20.

### Steps to Reproduce

After updating dataplane's container image from 0.20 to 0.21, webrtc, which was communicating via turn, intermittently disconnects.

**Expected behavior:** If there are no external factors, the connection should persist.

**Actual behavior:** The connection lasts for a few minutes and then disconnects.

### Versions

0.20 -> 0.21

#### Gateway API status

```
apiVersion: v1
items:
- apiVersion: gateway.networking.k8s.io/v1
  kind: Gateway
  metadata:
    name: gateway-udp
  spec:
    gatewayClassName: stunner-gatewayclass
    listeners:
    - allowedRoutes:
        namespaces:
          from: Same
      name: turn-udp-listener
      port: 17126
      protocol: TURN-UDP
- apiVersion: stunner.l7mp.io/v1
  kind: GatewayConfig
  metadata:
    name: stunner-gatewayconfig
  spec:
    authType: plaintext
    dataplane: default
    password: ---
    realm: stunner.l7mp.io
    userName: ---
- apiVersion: gateway.networking.k8s.io/v1
  kind: GatewayClass
  metadata:
    name: stunner-gatewayclass
  spec:
    controllerName: stunner.l7mp.io/gateway-operator
    description: STUNner is a WebRTC ingress gateway for Kubernetes
    parametersRef:
      group: stunner.l7mp.io
      kind: GatewayConfig
      name: stunner-gatewayconfig
- apiVersion: stunner.l7mp.io/v1
  kind: UDPRoute
  metadata:
    name: worker
  spec:
    parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gateway-udp
    rules:
    - backendRefs:
      - group: ""
        kind: Service
        name: worker
```

#### Operator logs 

```
I'll add the logs tomorrow after I try to reproduce it.
```

#### Gateway logs

```
I'll add the logs tomorrow after I try to reproduce it.
```
