### ISSUE TITLE
Load balancing does not work between gateway pods (stunner 1.0.0)

### ISSUE THREAD

**Issue by UladzimirTrehubenka** [l7mp/stunner#187]
After apply some load only one gateway pod is used (based on CPU usage) even if another one pod scaled up. If set minReplicas=2 (to have 2 gateway pods from the beginning) observed the same - only one is used. However for the legacy dataplane mode (stunner 0.17.0) load balancing is working across all gateway pods. **What are we missing here?**

Stunner (tried GCP and local cluster on kind + metallb) deployment:
```
helm install stunner-gateway-operator stunner/stunner-gateway-operator \
--create-namespace --namespace=stunner-system --version 1.0.0 \
--set stunnerGatewayOperator.dataplane.spec.enableMetricsEndpoint=true
```
Gateway deployment:
```
apiVersion: v1
kind: Namespace
metadata:
  name: stunner
---
apiVersion: v1
kind: Secret
metadata:
  name: stunner-auth-secret
  namespace: stunner
type: Opaque
stringData:
  type: static
  username: turnuser
  password: turnpass
---
apiVersion: stunner.l7mp.io/v1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig
  namespace: stunner
spec:
  realm: stunner.l7mp.io
  authRef:
    name: stunner-auth-secret
    namespace: stunner
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: stunner-gatewayclass
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    group: "stunner.l7mp.io"
    kind: GatewayConfig
    name: stunner-gatewayconfig
    namespace: stunner
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: stunner
  annotations:
    stunner.l7mp.io/enable-mixed-protocol-lb: "true"
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: TURN-UDP
    - name: tcp-listener
      port: 3478
      protocol: TURN-TCP
---
apiVersion: stunner.l7mp.io/v1
kind: UDPRoute
metadata:
  name: kms-media-plane
  namespace: stunner
spec:
  parentRefs:
    - name: gateway
  rules:
    - backendRefs:
        - name: kms-service
          namespace: default
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-gateway
  namespace: stunner
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 300
```
