### ISSUE TITLE
Feature: custom annotations to Stunner gateway services

### ISSUE THREAD

**Issue by Megzo** [l7mp/stunner#32]
In many cloud hosted Kubernetes environments `LoadBalancer` type services need custom annotations in order to tell the cloud provider what kind of external IP you want. A couple of examples:
 - Amazon EKS: https://docs.aws.amazon.com/eks/latest/userguide/network-load-balancing.html
 - Azure AKS: https://docs.microsoft.com/en-us/azure/aks/load-balancer-standard#additional-customizations-via-kubernetes-annotations
  - Digital Ocean: https://docs.digitalocean.com/products/kubernetes/how-to/configure-load-balancers/
  - MetalLB: https://metallb.universe.tf/usage/
  
 To that end it would be nice if we could add custom annotations to the services created by Stunner.
 My suggestion is to add a field to the Stunner `GatewayConfig` spec, e.g. like this:
 ```
 apiVersion: stunner.l7mp.io/v1alpha1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig
  namespace: default
spec:
  realm: stunner.l7mp.io
  authType: plaintext
  userName: "user-1"
  password: "pass-1"
  loadBalancerServiceAnnotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
 ``` 
 
 Then the operator can just copy the annotations under the `loadBalancerServiceAnnotations` key as-is to the created `LoadBalancer` service.
