### ISSUE TITLE
Panic on two gatewayclass definitions

### ISSUE THREAD

**Issue by imcom** [l7mp/stunner#35]
Run into a panic case where I defined to GatewayClass with distinct name and paramRef, is it feasible ? My use case is that I would like to have two separated stunner ingress instance one for staging and one for production. What's the official way to achieve this ?

Here is the crash scene

```
2022-09-16T06:29:41.903883429Z  DPANIC  renderer        odd number of arguments passed as key-value pairs for logging   {"ignored key": "\"/stunner-gatewayclass-prod\", \"/stunner-gatewayclass\""}
github.com/l7mp/stunner-gateway-operator/internal/renderer.(*Renderer).Start.func1
        /workspace/internal/renderer/renderer.go:73
panic: odd number of arguments passed as key-value pairs for logging

goroutine 79 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00092e180, {0xc000733400, 0x1, 0x1})
        /go/pkg/mod/go.uber.org/zap@v1.21.0/zapcore/entry.go:232 +0x446
go.uber.org/zap.(*Logger).DPanic(0x1728f71, {0x1778b51, 0x14ef6e0}, {0xc000733400, 0x1, 0x1})
        /go/pkg/mod/go.uber.org/zap@v1.21.0/logger.go:220 +0x59
github.com/go-logr/zapr.(*zapLogger).handleFields(0xc00040d1d0, 0x0, {0xc00082bec0, 0x1, 0x40af3d}, {0x0, 0x162e9a0, 0x1})
        /go/pkg/mod/github.com/go-logr/zapr@v1.2.3/zapr.go:147 +0xdea
github.com/go-logr/zapr.(*zapLogger).Info(0xc00040d1d0, 0x0, {0x17b4553, 0x0}, {0xc00082bec0, 0x1, 0x1})
        /go/pkg/mod/github.com/go-logr/zapr@v1.2.3/zapr.go:210 +0x8d
github.com/go-logr/logr.Logger.Info({{0x1962948, 0xc00040d1d0}, 0x2}, {0x17b4553, 0x125}, {0xc00082bec0, 0x1, 0x1})
        /go/pkg/mod/github.com/go-logr/logr@v1.2.3/logr.go:261 +0xd0
github.com/l7mp/stunner-gateway-operator/internal/renderer.(*Renderer).Render(0xc0000932c0, 0xc000302680)
        /workspace/internal/renderer/render_pipeline.go:49 +0x745
github.com/l7mp/stunner-gateway-operator/internal/renderer.(*Renderer).Start.func1()
        /workspace/internal/renderer/renderer.go:73 +0x17d
created by github.com/l7mp/stunner-gateway-operator/internal/renderer.(*Renderer).Start
        /workspace/internal/renderer/renderer.go:58 +0xb4
```

Thanks in advance!

**Comment by rg0now** [comment]
Yes, running multiple Gateway hierarchies side by side is supposed to work; in fact, your use of multiple gateway-classes is exactly the way we also had in mind. 

Problem is, this mode is not supported yet: what is really funny here is that the panic occurs in the operator exactly in the code where we try to warn that multiple gateway-classes are not supported: :-))
```
		log.Info("multiple gateway-class objects found %s: this is most probably UNINTENED - "+
			"the operator will attempt to render a configuration for each gateway-class but there "+
			"is no guarantee that this will not result in an error - this mode is UNSUPPORTED, "+
			"if unsure, remove one of the gateway-class objects!", strings.Join(names, ", "))
```
The fix is trivial but we'll have to make a new operator release.

**Comment by rg0now** [comment]
This should be fixed in https://github.com/l7mp/stunner-gateway-operator/releases/tag/v0.11.4, could you please give it a try? Make sure the operator is re-deployed, otherwise you won't get the fix. Multiple gateway-classes are still completely untested so we fully expect that you see further issues.  

Just to be entirely clear, the bug was in the operator, so the dataplane (`stunnerd`) does not need to be updated. 

Another note: if using multiple gateway-classes you should deploy *two* separate stunner dataplanes into separate namespaces. This will make sure that the two stunner dataplanes can run each with their own configuration. 

Here is how this should work:

1. Install stunner twice, each time into separate namespaces:
```
helm install stunner stunner/stunner --create-namespace --namespace=stunner-production
helm install stunner stunner/stunner --create-namespace --namespace=stunner-staging
```
2. Configure the gateway-class hierarchy for the staging namespace:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: stunner-gatewayclass-staging
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    name: stunner-gatewayconfig-staging
    namespace: stunner-staging
---
apiVersion: stunner.l7mp.io/v1alpha1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig-staging
  namespace: stunner-staging
spec:
  ...
```
3. Similarly for the production namespace:
```
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: GatewayClass
metadata:
  name: stunner-gatewayclass-production
spec:
  controllerName: "stunner.l7mp.io/gateway-operator"
  parametersRef:
    name: stunner-gatewayconfig-production
    namespace: stunner-staging-production
---
apiVersion: stunner.l7mp.io/v1alpha1
kind: GatewayConfig
metadata:
  name: stunner-gatewayconfig-production
  namespace: stunner-production
spec:
  ...
```
4. Now, whenever you add a Gateway with `gatewayClassName: stunner-gatewayclass-staging` the corresponding Gateway will be attached to the "staging" gatewayclass-hierarchy and the corresponding configuration will be picked up by the stunner dataplane running in the staging namespace, and similarly for the production hierarchy. I think you'll need separate UDPRoutes for both hierarchies but this shouldn't really be a problem.

Don't forget to leave a note here if this works, or reopen if it does not.
