### ISSUE TITLE
Question: Route based on host?

### ISSUE THREAD

**Issue by davhdavh** [l7mp/stunner#91]
I have tried searching the documentation, but it seems I cannot find information about how to have multiple distinct backends on the same frontend?

ie. 
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: udp-gateway
  namespace: default
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: UDP
```
and then n backend services:

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: iperf-server
  namespace: team1
spec:
  parentRefs:
    - name: udp-gateway
      namespace: default
  rules:
    - backendRefs:
        - name: iperf-server
          namespace: team1
```
and
```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: iperf-server
  namespace: team2
spec:
  parentRefs:
    - name: udp-gateway
      namespace: default
  rules:
    - backendRefs:
        - name: iperf-server
          namespace: team2
```

I don't really see anything in the [gateway spec](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1beta1.ParentReference) that would allow for this, and no attributes in stunner that would identify if traffic is sent to team1 or team2s iperf-server.

**Comment by rg0now** [comment]
Duplicate of #90

**Comment by rg0now** [comment]
Unfortunately, you're affected by the same problem as in #90 : cross-namespace Route bindings are not correctly implemented in STUNner (this is documented [here](https://github.com/l7mp/stunner/blob/main/docs/GATEWAY.md#udproute)). This was a simplification that made our life easier for the first couple of releases, but it is time to remove this subtlety for the better. We are actively working on fixing this, the progress is tracked [here](https://github.com/l7mp/stunner-gateway-operator/issues/30). 

Until then, it's best to just put all Gateways and UDPRoutes into the same namespace and everything should work fine.

**Comment by rg0now** [comment]
To actually answer your question: how you're trying to do it is exactly how it should be done, but until this far this has not been not possible due to a STUNner limitation that blocked UDPRoutes to attach to Gateways across a namespace boundary.

This should now fixed as of [e770d05](https://github.com/l7mp/stunner-gateway-operator/commit/e770d05b083fd174470f53dec16577b0d7e64046) in the [gateway-operator repo](https://github.com/l7mp/stunner-gateway-operator). Currently this change is only available on the [dev release channel](https://github.com/l7mp/stunner/blob/main/docs/INSTALL.md#development-version) from the `stunner/stunner-gateway-operator-dev` chart:

```console
helm install stunner-gateway-operator stunner/stunner-gateway-operator-dev --create-namespace --namespace=stunner-system 
```

The below worked for me perfectly:

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: udp-gateway
  namespace: default
spec:
  gatewayClassName: stunner-gatewayclass
  listeners:
    - name: udp-listener
      port: 3478
      protocol: UDP
      allowedRoutes:
        namespaces:
          from: All
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: iperf-server
  namespace: team1
spec:
  parentRefs:
    - name: udp-gateway
      namespace: default
  rules:
    - backendRefs:
        - name: iperf-server
          namespace: team1
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: UDPRoute
metadata:
  name: iperf-server
  namespace: team2
spec:
  parentRefs:
    - name: udp-gateway
      namespace: default
  rules:
    - backendRefs:
        - name: iperf-server
          namespace: team2
```

Note the `allowedRoutes` config in the Gateway, this makes sure that your Gateway accepts routes from all namespaces.

Can you please report back on your findings? Thanks!
